e2e:
  kind:
    # renovate: datasource=docker depName=kindest/node versioning=docker
    - 'v1.28.0'
    # renovate: datasource=docker depName=kindest/node versioning=docker
    - 'v1.28.0'
    # renovate: datasource=docker depName=kindest/node versioning=docker
    - 'v1.28.0'
    # renovate: datasource=docker depName=kindest/node versioning=docker
    - 'v1.28.0'
    # renovate: datasource=docker depName=kindest/node versioning=docker
    - 'v1.28.0'
    # renovate: datasource=docker depName=kindest/node versioning=docker
    - 'v1.28.0'
  gke:
    - 'v1.26.5'
  istio:
    # For Istio, we define combinations of Kind and Istio versions that will be
    # used directly in the test matrix `include` section.

    # renovate: datasource=docker depName=kindest/node versioning=docker
    - kind: 'v1.28.0'
      # renovate: datasource=docker depName=istio/istioctl versioning=docker
      istio: 'v1.19'
      # renovate: datasource=docker depName=kindest/node versioning=docker
    - kind: 'v1.28.0'
      # renovate: datasource=docker depName=istio/istioctl versioning=docker
      istio: 'v1.18'
      # renovate: datasource=docker depName=kindest/node versioning=docker
    - kind: 'v1.28.0'
      # renovate: datasource=docker depName=istio/istioctl versioning=docker
      istio: 'v1.17'
      # renovate: datasource=docker depName=kindest/node versioning=docker
    - kind: 'v1.28.0'
      # renovate: datasource=docker depName=istio/istioctl versioning=docker
      istio: 'v1.16'

integration:
  # renovate: datasource=docker depName=kindest/node versioning=docker
  kind: 'v1.28.0'
  # renovate: datasource=docker depName=kong versioning=docker
  kong-oss: '3.4.1'
  # renovate: datasource=docker depName=kong/kong-gateway versioning=docker
  kong-ee: '3.4.1.0'
