e2e:
  kind:
    - v1.23.12
    - v1.24.11
    - v1.25.10
    - v1.28.0
    - v1.26.3
    - v1.27.0
  gke:
    - v1.26.5
  istio:
    - kubernetes-version: v1.28.0
      istio-version: v1.19
    - kubernetes-version: v1.27.3
      istio-version: v1.18
    - kubernetes-version: v1.26.6
      istio-version: v1.17
    - kubernetes-version: v1.25.11
      istio-version: v1.16
