e2e:
  kind:
    # To get the latest:
    #   cat .github/test_dependencies.yaml | yq -ojson '.e2e.kind' | jq -c 'first(.[])'
    # To get all:
    #   cat .github/test_dependencies.yaml | yq -ojson '.e2e.kind' | jq -c
    - 'v1.28.0'
    - 'v1.27.0'
    - 'v1.26.3'
    - 'v1.25.10'
    - 'v1.24.11'
    - 'v1.23.12'
  gke:
    # cat .github/test_dependencies.yaml | yq -ojson '.e2e.gke' | jq -c
    - 'v1.26.5'
  istio:
    # For Istio, we define combinations of Kind and Istio versions that will be
    # used directly in the test matrix `include` section.
    # cat .github/test_dependencies.yaml | yq -ojson '.e2e.istio' | jq -c
    - kind: 'v1.28.0'
      istio: 'v1.19'
    - kind: 'v1.27.3'
      istio: 'v1.18'
    - kind: 'v1.26.6'
      istio: 'v1.17'
    - kind: 'v1.25.11'
      istio: 'v1.16'

integration:
  # cat .github/test_dependencies.yaml | yq -ojson '.integration.kind' | jq -c
  kind: 'v1.28.0'
  # cat .github/test_dependencies.yaml | yq -ojson '.integration.kong-oss' | jq -c
  kong-oss: '3.4'
  # cat .github/test_dependencies.yaml | yq -ojson '.integration.kong-ee' | jq -c
  kong-ee: '3.4'
