name: Regenerate on deps bump

on:
  pull_request:
    types:
      - labeled

jobs:
  regenerate:
    if: contains(github.event.*.labels.*.name, 'renovate/auto-regenerate')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup golang
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: regenerate
        run: make generate

      - name: commit changes (if any)
        run: |
          git config --global user.name 'team-k8s-bot'
          git config --global user.email 'team-k8s+github-bot@konghq.com'
          git diff --exit-code || git commit -am "chore: regenerate on deps update"
          git push
